# See https://docs.rubocop.org/rubocop/configuration

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/MethodLength:
  Exclude:
    - db/**/*

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Exclude: 
    - spec/views/**/*

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Exclude: 
    - spec/views/**/*

RSpec/MultipleMemoizedHelpers:
  Max: 7

Metrics/AbcSize:
  Exclude:
    - db/**/*

Metrics/CyclomaticComplexity:
  Exclude:
    - db/**/*

Metrics/PerceivedComplexity:
  Exclude:
    - db/**/*

Performance/TimesMap:
  Exclude:
    - db/**/*

Rails/SkipsModelValidations:
  Exclude:
    - db/**/*